name: Build Dev APK

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  Gradle:
    if: endsWith(github.event.head_commit.message, 'workflow build') && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ensure Gradle wrapper exists
      run: |
        if [ ! -f "gradlew" ]; then
          echo "Gradle wrapper missing, generating..."
          wget https://services.gradle.org/distributions/gradle-9.4.1-bin.zip
          unzip -q gradle-9.4.1-bin.zip
          ./gradle-9.4.1/bin/gradle wrapper --gradle-version 9.4.1
        else
          echo "Gradle wrapper already exists"
        fi

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Build Debug APK
      run: ./gradlew assembleDebug --parallel --build-cache

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apks
        path: app/build/outputs/apk/debug/*.apk
        if-no-files-found: error
